[build]
  publish = "dist"
  command = "npm run build"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.environment]
  NODE_VERSION = "18"
  NPM_FLAGS = "--prefer-offline --no-audit"

# Prevent function errors since we don't have working functions yet
[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"